'use strict';
const cfg=JSON.parse(document.getElementById('config').textContent),code=cfg.code;
const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const titles={B16:'把最终稿，确认清楚。',B10:'这一周，经营情况一目了然。',B05:'从培训材料，到可用的试题。',B12:'归还之后，检查再出库。',B18:'这个月，还缺哪份资料？',B17:'现场变更，有条理地交接。',C01:'把你的真实经历，说清楚。',C13:'每一份照片，找到它的副本。',C16:'先看线盒，再补缺线。',C18:'记得上次，也照顾今天。'};
const defaults={B16:{name:'秋日活动宣传单',customer:'林女士',content:'秋日好物节\n9月20日—9月30日\n每一份美好，值得收藏。',reason:''},B10:{period:'2026-09-14 至 2026-09-20',sales:'12800',refund:'680',ads:'950',reason:''},B05:{topic:'新人饮品知识',material:'示例教材 第1页：燕麦拿铁使用燕麦奶。\n第2页：门店标准中杯为350毫升。',question:'燕麦拿铁使用哪种奶？',answer:'燕麦奶',source:'第1页',reason:''},B12:{equipment:'A-001 主音箱',reason:'',returnNote:'外观待检查'},B18:{client:'青禾工作室',period:'2026-09',filename:'9月银行流水.pdf',reason:''},B17:{name:'房间A新增插座点位',location:'一层A室',qty:'2',price:'180',attachment:'现场照片-01.jpg',reason:''},C01:{job:'跨境电商运营',experience:'每周整理广告搜索词，与主管核对后调整投放词。',draft:'',reason:''},C13:{name:'家庭照片核对',disk:'旅行照片盘',reason:''},C16:{stockMode:'known',color:'310',stock:'1',need:'1.5',used:'0.5'},C18:{name:'窗边龟背竹',date:'2026-09-27',note:'表土偏干，观察叶片状态'}};
function initial(){return {form:{...defaults[code]},status:'draft',role:'user',events:[],version:1,history:[],items:['未提交','未提交'],selected:'0',stock:null,need:null,purchase:null,plants:[],backup:null,checked:false,report:null,revision:0,confirmedVersion:null};}
const recordMeta={B16:['订单','name'],B10:['报告周期','period'],B05:['培训任务','topic'],B12:['器材','equipment'],B18:['客户资料清单','client'],B17:['变更事项','name'],C01:['简历任务','job'],C13:['核对任务','name'],C16:['色号','color'],C18:['植物','name']};
function freshWorkspace(){return {version:3,code,current:'task-1',nextId:2,records:[{id:'task-1',state:initial()}]};}
let workspace=freshWorkspace(),s=workspace.records[0].state,message='',isError=false,pendingBackup=null,storageWarning='';
function syncCurrent(){workspace.records.find(r=>r.id===workspace.current).state=s;}
function exportWorkspace(){syncCurrent();return JSON.parse(JSON.stringify({...workspace,records:workspace.records.map(r=>({...r,state:{...r.state,backup:null}}))}));}
function persist(){syncCurrent();try{sessionStorage.setItem('user-prototype-v3-'+code,JSON.stringify(exportWorkspace()));storageWarning='';}catch{storageWarning='浏览器暂时无法保存，刷新可能丢失本次修改。';}if($('saveState'))$('saveState').textContent=storageWarning||'本次会话已保存';}
try{
 const saved=JSON.parse(sessionStorage.getItem('user-prototype-v3-'+code));
 if(saved?.code===code&&saved.version===3&&Array.isArray(saved.records)&&saved.records.length&&saved.records.every(r=>r.state?.form&&Array.isArray(r.state.events))&&saved.records.some(r=>r.id===saved.current))workspace=saved;
 else{const old=JSON.parse(sessionStorage.getItem('user-prototype-v2-'+code));if(old?.form&&Array.isArray(old.events))workspace.records[0].state={...initial(),...old,form:{...defaults[code],...old.form},backup:null};}
 s=workspace.records.find(r=>r.id===workspace.current).state;
}catch{storageWarning='未能读取上次会话，当前打开初始示例。';}
function ownsList(){return code==='B16'?s.role==='user':code==='B18'?s.role==='staff':true;}
function recordName(record){const f=record.state.form;return (code==='B18'?[f.client,f.period].filter(Boolean).join(' · '):code==='C18'?(record.state.plants[0]?.name||f.name):f[recordMeta[code][1]])||'未命名'+recordMeta[code][0];}
function recordStatus(record){const st=record.state;
 if(code==='B18')return st.items.every(x=>x==='通过')?'资料已齐':st.items.some(x=>x==='等待审核')?'待审核':'待补资料';
 if(code==='C16')return st.need===null?'待核对':st.stock===null?'数量待核':Math.max(0,st.need-st.stock)>0?'需补线':'库存充足';
 if(code==='C18')return st.plants.length?(st.nextDate?'检查日 '+st.nextDate:'已建档'):'待建档';
 return ({draft:'草稿',submitted:'已提交',sent:'待确认',rejected:'退回修改',confirmed:'已确认',checked:'已复核',delivered:'待验收',accepted:'已验收',revision:'待修订',returned:'待检查',damaged:'待维修',ready:'可租',out:'已出库',scanned:'待复核',verified:'复核完成'})[st.status]||st.status;
}
function renderWorkspace(){const noun=recordMeta[code][0];
 if(!ownsList())return `<section class="task-context"><span>${esc(recordName({state:s}))}</span>${badge(code==='B16'?'本订单确认入口':'本客户资料入口')}</section>`;
 return `<section class="workspace-bar"><div class="workspace-heading"><div><div class="eyebrow">MY RECORDS</div><h2>我的${esc(noun)} <span class="count">${workspace.records.length}</span></h2></div>${btn('新建'+noun,'newRecord',workspace.records.length>=100,true)}</div><label class="field"><span>选择${esc(noun)}</span><select id="recordPicker" aria-label="选择${esc(noun)}">${workspace.records.map(r=>`<option value="${esc(r.id)}" ${r.id===workspace.current?'selected':''}>${esc(recordName(r))} · ${esc(recordStatus(r))}</option>`).join('')}</select></label><div class="save-line"><span id="saveState">${esc(storageWarning||'本次会话已保存')}</span><span>不同记录的进度分别保留</span></div>${workspace.records.length>1?`<details class="record-overview"><summary>查看全部${esc(noun)}进度</summary>${workspace.records.map(r=>row(recordName(r),recordStatus(r))).join('')}</details>`:''}</section>`;
}
function selectRecord(id){syncCurrent();const record=workspace.records.find(r=>r.id===id);if(!record)return;const role=s.role;workspace.current=id;s=record.state;s.role=role;pendingBackup=null;notify('已切换到 '+recordName(record));persist();render();}
function newRecord(){guard(ownsList(),'请在工作人员入口管理记录。');guard(workspace.records.length<100,'本轮原型最多保留100条记录，请先导出后再整理。');syncCurrent();const role=s.role;const state=initial();state.form=Object.fromEntries(Object.keys(defaults[code]).map(k=>[k,'']));if(code==='C16')state.form.stockMode='known';state.role=role;const record={id:'task-'+workspace.nextId++,state};workspace.records.push(record);workspace.current=record.id;s=state;pendingBackup=null;notify('已新建'+recordMeta[code][0]+'，其他记录保持不变。');}
function serviceHistory(){if(!['B10','B05','B17','C01'].includes(code))return '';const versions=s.deliveries||[];
 const reopen=user()&&s.status!=='draft';
 return card('交付版本与资料修改',`${reopen?`<p class="muted">如果原始资料填错或需要补充，可以修改后重新提交。已交付的版本会保留。</p>${btn('修改提交资料','amend',false,true)}`:''}${versions.length?versions.map((v,i)=>`<details class="delivery-version"><summary>交付版本 ${i+1}${i===versions.length-1?' · 最近一次':''}</summary><div class="document">${esc(Object.entries(v).map(([k,value])=>(({period:'周期',sales:'实收',refund:'退款',ads:'广告支出',net:'实收减退款',topic:'主题',question:'题目',answer:'答案',source:'出处',name:'事项',location:'位置',qty:'数量',price:'单价',total:'金额',attachment:'附件',job:'岗位',draft:'正文'})[k]||k)+'：'+value).join('\n'))}</div></details>`).join(''):empty('首次交付后会在这里保留版本。')}`,'history-panel');}
function validateBackup(b){
 const fail=()=>{throw Error('备份格式不兼容或记录不完整，现有记录未改变。');};
 if(!b||b.code!==code)fail();
 const half=n=>n===null||(Number.isFinite(n)&&n>=0&&Number.isInteger(n*2));
 const events=e=>Array.isArray(e)&&e.length<=2000&&e.every(x=>x&&typeof x.text==='string'&&typeof x.time==='string');
 if(b.version===2){const d=b.data;if(!d||!events(d.events))fail();const state=initial();state.events=d.events;
  if(code==='C16'){if(!half(d.stock)||!half(d.need)||typeof d.color!=='string')fail();guard(!workspace.records.some(r=>r.id!==workspace.current&&r.state.form.color===d.color),'色号已存在，请先选择原色号再恢复。');state.stock=d.stock;state.need=d.need;state.form.color=d.color;state.form.stock=String(d.stock??'');state.form.need=String(d.need??'');state.form.stockMode=d.stock===null?'unknown':'known';state.status=d.need===null?'draft':'ready';}
  else{if(!Array.isArray(d.plants)||d.plants.length>1||!d.plants.every(x=>x&&typeof x.name==='string')||(d.nextDate!==null&&typeof d.nextDate!=='string'))fail();state.plants=d.plants;state.nextDate=d.nextDate;state.form.name=d.plants[0]?.name||'';state.form.date=d.nextDate||'';state.status=d.plants.length?'ready':'draft';}
  return {kind:'legacy',state,summary:'V2单条备份：仅替换当前'+recordMeta[code][0]+'，其他记录保留'};
 }
 if(b.version!==3||!Array.isArray(b.records)||!b.records.length||b.records.length>100||!Number.isInteger(b.nextId))fail();
 const ids=new Set(),colors=new Set();let highest=0;
 for(const r of b.records){if(!r||typeof r.id!=='string'||!/^task-[1-9][0-9]*$/.test(r.id)||ids.has(r.id))fail();ids.add(r.id);highest=Math.max(highest,Number(r.id.slice(5)));const st=r.state;
  if(!st||!st.form||!Object.keys(defaults[code]).every(k=>typeof st.form[k]==='string')||!events(st.events)||!['draft','ready'].includes(st.status)||!['user','staff'].includes(st.role)||!Array.isArray(st.history)||!Array.isArray(st.items)||!Array.isArray(st.plants))fail();
  if(code==='C16'){if(st.status==='ready'){guard(!colors.has(st.form.color),'色号已存在，备份包含重复色号，现有记录未改变。');colors.add(st.form.color);}if(!half(st.stock)||!half(st.need)||(st.purchase!==null&&(!half(st.purchase)||st.stock===null||st.purchase>st.stock))||!['known','unknown'].includes(st.form.stockMode))fail();}
  else if(st.plants.length>1||!st.plants.every(x=>x&&typeof x.name==='string')||(st.nextDate!=null&&(typeof st.nextDate!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(st.nextDate))))fail();
 }
 if(!ids.has(b.current)||b.nextId<=highest)fail();
 return {kind:'collection',data:JSON.parse(JSON.stringify(b)),summary:'共 '+b.records.length+' 条'+recordMeta[code][0]+'；确认后替换当前整个列表'};
}
async function readBackup(event){const f=event.target.files[0];if(!f)return;const source=JSON.stringify(exportWorkspace());pendingBackup=null;
 try{guard(f.size<1000000,'备份文件过大，请选择小于1MB的原型备份。');const data=JSON.parse(await f.text());guard(source===JSON.stringify(exportWorkspace()),'读取期间记录发生变化，请重新选择备份。');pendingBackup={...validateBackup(data),source};notify('备份已读取，请核对替换范围后确认恢复。');}
 catch(e){pendingBackup=null;notify(e instanceof SyntaxError?'备份文件无法读取，请选择本原型导出的完整备份。现有记录未改变。':e.message,true);}render();
}
function field(label,key,type='text',options={}){
 const pending=['submitted','revision'].includes(s.status);
 const fixed={B10:['period','sales','refund','ads'],B05:['topic','material'],B17:['name','location','qty','price','attachment'],C01:['job','experience']}[code]||[];
 const editableByStaff=['B10','B17'].includes(code);
 const locked=(fixed.includes(key)&&(user()?s.status!=='draft':editableByStaff?!pending:true))||(code==='B12'&&key==='equipment'&&s.status!=='draft')||(code==='C16'&&key==='color'&&s.status!=='draft')||(code==='B18'&&['client','period'].includes(key)&&(!(!user()&&s.status==='draft')))||(!user()&&((code==='B05'&&['question','answer','source'].includes(key))||(code==='C01'&&key==='draft'))&&!pending);
 options={...options,disabled:options.disabled||locked};return `<label class="field"><span>${esc(label)}</span>${type==='textarea'?`<textarea aria-label="${esc(label)}" data-field="${key}" ${options.disabled?'disabled':''}>${esc(s.form[key])}</textarea>`:`<input aria-label="${esc(label)}" data-field="${key}" type="${type}" value="${esc(s.form[key])}" ${type==='number'?'min="0" step="0.5"':''} ${options.disabled?'disabled':''}>`}</label>`;}
const btn=(label,action,disabled=false,secondary=false)=>`<button type="button" data-action="${action}" ${disabled?'disabled':''} class="${secondary?'':'primary'}">${esc(label)}</button>`;
const card=(title,body,cls='')=>{if(['反馈与确认','样题反馈','校对与修订'].includes(title))cls+=' feedback-panel';if(['操作记录','交付进展','流转记录','收件记录','交接记录','服务进展','核对记录','库存记录','养护时间线'].includes(title))cls+=' history-panel';return `<section class="card ${cls}"><h2>${esc(title)}</h2>${body}</section>`;};
const badge=t=>`<span class="badge">${esc(t)}</span>`;
const empty=t=>`<div class="empty">${esc(t)}</div>`;
const row=(a,b)=>`<div class="item"><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`;
function log(text){s.events.unshift({text,time:new Date().toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})});}
function timeline(){return `<ul class="timeline" id="history">${s.events.length?s.events.map(e=>`<li>${esc(e.text)}<small>${esc(e.time)}</small></li>`).join(''):'<li>完成第一个任务后，进展会出现在这里。</li>'}</ul>`;}
function notify(t,error=false){message=t;isError=error;}
function required(...keys){for(const k of keys)if(!String(s.form[k]??'').trim())throw Error('请补充空白资料，再继续。');}
function number(k){const value=s.form[k];if(String(value).trim()===''||!Number.isFinite(Number(value))||Number(value)<0)throw Error('请输入不小于0的有效数字。');return Number(value);}
function guard(condition,text){if(!condition)throw Error(text);}
function money(n){return Number(n).toFixed(2);}
function user(){return s.role==='user';}
function download(name,data,type='application/json'){const text=typeof data==='string'?data:JSON.stringify(data,null,2);const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function reportButton(label='下载结果摘要'){return btn(label,'download',s.status==='draft'&&!(s.deliveries?.length||s.history.length),true);}
function renderB16(){
 const labels={draft:'待发送',sent:'等待客户确认',rejected:'客户退回修改',confirmed:'客户已确认',checked:'已完成印前复核'};
 if(!user()&&s.status==='draft')return card('等待校样',empty('尚未收到待确认校样，请等待店员发送。'));
 if(!user())return `<div class="mobile">${card('请核对这份校样',`<div class="statusline">${badge('版本 V'+s.version)}<span>${esc(s.form.name)}</span></div><div class="proof"><small>PROOF · 校样</small>${esc(s.form.content)}</div><p class="note">确认后，店员将据此进行印前核对。如需修改，请写明位置和内容。</p>${s.reason?`<p class="hint">上次修改意见：${esc(s.reason)}</p>`:''}${field('修改意见','reason','textarea')}<div class="actions">${btn('确认这一版','confirm',s.status!=='sent')}${btn('退回修改','reject',s.status!=='sent',true)}</div>`)}${card('确认进展',badge(labels[s.status])+timeline())}</div>`;
 return `<div class="grid"><div>${card('订单与当前校样',`${field('订单名称','name','text',{disabled:!['draft','rejected'].includes(s.status)})}${field('确认客户','customer','text',{disabled:!['draft','rejected'].includes(s.status)})}${field('校样内容','content','textarea',{disabled:!['draft','rejected'].includes(s.status)})}<div class="actions">${btn('保存并发送确认','send',!['draft','rejected'].includes(s.status))}${btn('修改并创建新版','newVersion',s.status==='draft',true)}</div><p class="note">使用可编辑的文字校样体验流程；不会给客户发送消息。</p>`)}${card('版本记录',s.history.length?s.history.map(v=>`<details class="delivery-version"><summary>V${v.version} · ${esc(v.status)}</summary><div class="document">${esc(v.content)}</div></details>`).join(''):empty('发送后会保留版本记录。'))}</div><div>${card('订单进展',`${badge(labels[s.status])}${s.waiting?'<p class="hint">等待重新确认</p>':''}${s.reason?`<p>客户意见：${esc(s.reason)}</p>`:''}<div class="stat">V${s.version}</div><p class="muted">${esc(s.form.name)}</p><div class="actions">${btn('登记印前复核','printCheck',s.status!=='confirmed')}${reportButton('下载确认记录')}</div><p class="note">只有当前版本得到客户确认后，才能登记印前复核。</p>`,'highlight')}${card('操作记录',timeline())}</div></div>`;
}
function renderB10(){
 const ready=!!s.report;
 return `<div class="grid"><div>${card(user()?'提交本期经营资料':'交付人员 · 核对资料',`${field('报告周期','period')}<div class="fields">${field('本期实收（元）','sales','number')}${field('本期退款（元）','refund','number')}${field('广告支出（元）','ads','number')}</div><p class="note">样报使用本期发生额。此原型用手填汇总体验资料交接，正式交付须核对订单、退款与广告来源文件。</p><div class="actions">${user()?btn('提交本期资料','submit',s.status!=='draft'):btn('生成样报','produce',!['submitted','revision'].includes(s.status))}</div>`)}${ready?card('反馈与确认',`${field('修订意见','reason','textarea')}<div class="actions">${btn('确认本期报告','accept',s.status!=='delivered'||!user())}${btn('请求重新核对','revise',s.status!=='delivered'||!user(),true)}${reportButton()}</div>`):''}</div><div>${card('本期经营周报',ready?`<p>${esc(s.report.period)}</p><div class="metrics"><div class="metric"><small>实收减退款</small><strong>${money(s.report.net)}</strong></div><div class="metric"><small>广告支出</small><strong>${money(s.report.ads)}</strong></div><div class="metric"><small>退款发生额</small><strong>${money(s.report.refund)}</strong></div></div><p class="note">实收 ${money(s.report.sales)} − 退款 ${money(s.report.refund)} = ${money(s.report.net)}。未提供商品成本、平台费等，不计算净利润。</p>${badge(s.status==='accepted'?'已验收':s.status==='revision'?'等待重新核对':'待确认')}`:empty(s.status==='draft'?'提交资料后，交付人员会核对并准备报告。':'资料已提交，等待交付人员核对。'))}${card('交付进展',timeline())}</div></div>`;
}
function renderB05(){return `<div class="grid"><div>${card(user()?'这次要培训什么？':'审题工作台',user()?`${field('培训主题','topic')}${field('教材内容','material','textarea')}<p class="note">先确认小样，再完成100题包。本原型以一道可编辑样题体验审核，不生成完整题库。</p>${btn('提交出题需求','submit',s.status!=='draft')}`:`<h3>本次提交：${esc(s.form.topic)}</h3><div class="document">${esc(s.form.material)}</div><p class="note">请对照以上教材逐题核实。</p>${field('题目','question','textarea')}${field('正确答案','answer')}${field('教材出处','source')}${s.reason?`<p class="hint">客户意见：${esc(s.reason)}</p>`:''}${btn('交付已审样题','produce',!['submitted','revision'].includes(s.status))}<p class="note">审题人需对照教材确认答案和出处后交付。</p>`)}${user()&&s.report?card('样题反馈',`${field('修订意见','reason','textarea')}<div class="actions">${btn('确认样题口径','accept',s.status!=='delivered')}${btn('退回修订','revise',s.status!=='delivered',true)}</div>`):''}</div><div>${card('样题预览',s.report?`<div class="document">${esc(s.report.question)}\n\n答案：${esc(s.report.answer)}\n出处：${esc(s.report.source)}</div><p>${badge(s.status==='accepted'?'样题已确认':s.status==='revision'?'等待修订':'等待客户确认')}</p>${reportButton('下载样题摘要')}`:empty('提交教材后，等待审题人交付校准样题。'))}${card('交付进展',timeline())}</div></div>`;}
function renderB12(){const status={draft:'租赁中',returned:'待检查',damaged:'待维修',ready:'可租',out:'已出库'};return `<div class="grid"><div>${card('本次归还',`${field('器材编号与名称','equipment')}${field('交接备注','returnNote','textarea')}${badge(status[s.status])}<div class="actions">${btn('登记归还','return',!['draft','out'].includes(s.status))}${btn('检查完成，恢复可租','ready',s.status!=='returned')}${btn('发现损坏','damage',s.status!=='returned',true)}</div>${s.status==='damaged'?`<p class="hint">先完成维修，再由仓管复检。</p>${btn('维修完成，重新待检','repair')}`:''}`)}${card('下一单出库',`<p>下一单：社区活动 · 9月22日 09:00</p><p class="muted">出库前需要器材已归还且检查通过。</p>${btn('确认下一单出库','out',s.status!=='ready')}`)}</div><div>${card('当前可用状态',`<div class="stat">${s.status==='ready'?'1':'0'} <small>件可立即出库</small></div><p>${esc(s.form.equipment)}</p><p>${badge(status[s.status])}</p><p class="note">首版原型为每件序列号器材单独保存流转；实际预约还需核对时间冲突。</p>`,'highlight')}${card('流转记录',timeline()+reportButton('下载流转摘要'))}</div></div>`;}
function renderB18(){const names=['本期银行流水','本期业务票据'];const complete=s.items.every(x=>x==='通过');return `<div class="grid"><div>${card(user()?(s.form.client+' · '+s.form.period):'记账员 · 本期审核',`${!user()?`${field('客户名称','client')}${field('资料期间','period')}${btn('保存客户与期间','saveClient',s.status!=='draft',true)}`:''}<label class="field"><span>资料项目</span><select id="item" aria-label="资料项目">${names.map((n,i)=>`<option value="${i}" ${s.selected==i?'selected':''}>${n}</option>`).join('')}</select></label>${user()?`${field('资料文件名','filename')}<p class="note">当前仅登记示例文件名，不上传真实资料。</p>${btn('提交资料','upload',s.items[+s.selected]==='等待审核'||s.items[+s.selected]==='通过')}`:`<p>已提交文件：${esc(s.files?.[s.selected]||'尚未提交')}</p>${field('退回原因','reason','textarea')}<div class="actions">${btn('审核通过','approve',s.items[+s.selected]!=='等待审核')}${btn('退回补充','reject',s.items[+s.selected]!=='等待审核',true)}</div>`}${s.reasons?.[s.selected]?`<p class="hint">退回说明：${esc(s.reasons[s.selected])}</p>`:''}`)}</div><div>${card('资料清单',names.map((n,i)=>row(n,s.items[i])).join('')+`<p>${badge(complete?'本期资料已齐':'尚有资料待提交或审核')}</p><p class="note">上传后还需记账员审核，待审资料不计为齐套。</p>`,'highlight')}${card('收件记录',timeline()+reportButton('下载资料状态清单'))}</div></div>`;}
function renderB17(){const status={draft:'现场草稿',submitted:'办公室待复核',delivered:'申请包已生成',accepted:'已接收，待外部审批',revision:'退回补充'};return `<div class="grid"><div>${card(user()?'记录现场变更':'办公室复核',`${field('变更事项','name')}${field('施工位置','location')}<div class="fields">${field('数量','qty','number')}${field('单价（元）','price','number')}</div>${field('附件名称','attachment')}${field('补充说明','reason','textarea')}<p class="note">附件为示例名称；原型不上传照片。金额按当前输入计算。</p>${user()?btn('提交办公室复核','submit',s.status!=='draft'):btn('审核并生成申请包','produce',!['submitted','revision'].includes(s.status))}`)}</div><div>${card('申请包',s.report?`<div class="document">变更申请 · V${s.version}\n${esc(s.report.name)}\n位置：${esc(s.report.location)}\n数量 ${s.report.qty} × 单价 ${money(s.report.price)}\n金额 ${money(s.report.total)} 元\n附件：${esc(s.report.attachment)}</div><p>${badge(status[s.status])}</p><div class="actions">${btn('登记接收','accept',s.status!=='delivered')}${btn('退回补充','revise',s.status!=='delivered',true)}${reportButton('下载申请摘要')}</div>`:empty(status[s.status]))}${card('交接记录',timeline())}</div></div>`;}
function renderC01(){return `<div class="grid"><div>${card(user()?'准备你的岗位简历':'顾问审阅工作台',`${field('目标岗位','job')}${field('真实经历','experience','textarea')}${!user()?`${field('审阅稿','draft','textarea')}<p class="note">请核实职责边界和事实，不添加未经本人确认的数字。</p>${s.reason?`<p class="hint">用户意见：${esc(s.reason)}</p>`:''}${btn('交付审阅稿','produce',!['submitted','revision'].includes(s.status))}`:`<p class="note">提交一个目标岗位和真实经历，顾问会追问并整理。可先隐去联系方式。</p>${btn('提交给顾问','submit',s.status!=='draft')}`}`)}${user()&&s.report?card('校对与修订',`${field('修改意见','reason','textarea')}<div class="actions">${btn('确认终稿','accept',s.status!=='delivered')}${btn('请求修订','revise',s.status!=='delivered',true)}</div>`):''}</div><div>${card('你的岗位版本',s.report?`<div class="document">${esc(s.report.job)}\n\n${esc(s.report.draft)}</div><p>${badge(s.status==='accepted'?'终稿已确认':s.status==='revision'?'等待顾问修订':'请核对事实和表达')}</p>${reportButton('下载简历文本')}`:empty('提交后，顾问审阅稿会出现在这里。'))}${card('服务进展',timeline())}</div></div>`;}
function renderC13(){return `<div class="grid"><div>${card('选择本次核对范围',`${field('报告名称','name')}${field('磁盘别名','disk')}<div class="item"><span>示例：旅行照片盘</span><span>3个文件</span></div><div class="item"><span>示例：家庭备份盘</span><span>3个文件</span></div><p class="note">原型只扫描内置示例清单，不访问你的硬盘，也不删除文件。</p>${btn('扫描示例目录','scan')}`)}${card('遇到无法访问的副本',`<p>无法读取时保留“待复核”，重新连接后才能更新结论。</p>${btn('重新连接并复核','recheck',s.status!=='scanned')}`)}</div><div>${card('副本核对报告',s.report?`<div class="statusline"><h3>${esc(s.report.name)}</h3>${badge(s.status==='verified'?'复核完成':'有1项待复核')}</div>${row('海边.jpg ↔ 旅行-01.jpg','内容一致')}${row('生日.jpg ↔ 生日副本.jpg','哈希匹配，未逐字节复核')}${row('合影.jpg ↔ 备份合影.jpg',s.status==='verified'?'内容一致':'待重新连接')}<p class="note">报告只说明本次示例检查结果，历史记录不证明当前备份仍存在。</p>${reportButton('下载核对报告')}`:empty('开始扫描后，在这里查看匹配和需要进一步核对的文件。'))}${card('核对记录',timeline())}</div></div>`;}
function backupUI(){return card('备份与恢复',`<p class="muted">备份整个列表及每条记录的进度，恢复前先核对替换范围。</p><div class="actions">${btn('下载备份','backup',false,true)}</div><label class="field file"><span>选择备份文件</span><input id="restoreFile" type="file" accept=".json,application/json"></label>${pendingBackup?`<p>${badge('备份可读取')} · ${esc(pendingBackup.summary)}</p>${btn('确认恢复','restore')}${btn('取消恢复','cancelRestore',false,true)}`:''}<p class="note">恢复前建议先下载当前备份。新备份覆盖整个列表；V2旧备份仅替换当前记录。</p>`,'backup-panel');}
function stockResultCurrent(){return s.form.stockMode==='known'&&s.stock!==null&&s.need!==null&&s.form.stock.trim()!==''&&s.form.need.trim()!==''&&Number(s.form.stock)===s.stock&&Number(s.form.need)===s.need;}
function refreshStockActions(){if(code!=='C16')return;const current=stockResultCurrent();for(const action of ['purchase','consume','undoPurchase']){const el=document.querySelector('[data-action="'+action+'"]');if(el)el.disabled=!current||(action==='purchase'?(s.purchase!==null||s.need<=s.stock):action==='undoPurchase'?s.purchase===null:false);}const hint=$('stockResultHint');if(hint)hint.textContent=current?'':s.form.stockMode==='unknown'?'数量待核，请核实库存后重新生成清单。':'输入已修改，请重新生成缺线清单。';}
function renderC16(){const known=s.need!==null;const shortage=known&&s.stock!==null?Math.max(0,s.need-s.stock):null;return `<div class="grid"><div>${card('这次准备哪个色号？',`${field('色号','color')}<label class="field"><span>库存情况</span><select id="stockMode" aria-label="库存情况"><option value="known" ${s.form.stockMode!=='unknown'?'selected':''}>数量已知</option><option value="unknown" ${s.form.stockMode==='unknown'?'selected':''}>数量待核</option></select></label><div class="fields">${field('现有库存（束）','stock','number',{disabled:s.form.stockMode==='unknown'})}${field('项目需求（束）','need','number')}</div><p class="note">以半束为单位；同一活动项目可分别添加多个色号；余量不清时选择数量待核。</p>${btn('生成缺线清单','calculate')}`)}${backupUI()}</div><div>${card('缺线清单',known?`<p>${esc(s.form.color)} · 当前项目</p><p id="stockResultHint" class="note">${stockResultCurrent()?'':s.form.stockMode==='unknown'?'数量待核，请核实库存后重新生成清单。':'输入已修改，请重新生成缺线清单。'}</p><div class="stat">${shortage===null?'数量待核':shortage>0?'需购买 '+shortage+' 束':'当前库存充足'}</div><p>库存 ${s.stock===null?'待核':s.stock+' 束'} · 需求 ${s.need} 束</p><div class="actions">${btn('确认已买并入库','purchase',!stockResultCurrent()||shortage===null||shortage===0||s.purchase!==null)}${btn('撤销本次入库','undoPurchase',!stockResultCurrent()||s.purchase===null,true)}</div>`:empty('填写库存和需求，生成本次缺线清单。'),'highlight')}${known?card('实际用线',`${field('实际用量（束）','used','number')}${btn('登记实际耗用','consume',!stockResultCurrent())}`):''}${card('库存记录',timeline())}</div></div>`;}
function renderC18(){return `<div class="mobile"><div class="grid"><div>${card('我的植物',`${field('植物名称','name')}<div class="plant" aria-hidden="true">🌿</div>${btn('保存植物','savePlant')}`)}${backupUI()}</div><div>${card(s.plants[0]?.name||'先添加一盆植物',s.plants.length?`${field('检查备注','note','textarea')}<div class="actions">${btn('记录检查完成','check')}${btn('记录已浇水','water',false,true)}</div><hr><h3>下一次检查</h3>${field('检查日期','date','date')}${btn('保存检查日期','schedule',false,true)}${s.nextDate?`<p>${badge('下次检查 '+s.nextDate)}</p>`:''}<p class="note">检查不等于浇水；提醒日期由你决定。此原型不发送系统通知。</p>`:empty('保存植物后，可以记录检查、浇水并安排下次检查。'))}${card('养护时间线',timeline())}</div></div></div>`;}
const renderers={B16:renderB16,B10:renderB10,B05:renderB05,B12:renderB12,B18:renderB18,B17:renderB17,C01:renderC01,C13:renderC13,C16:renderC16,C18:renderC18};
const roleLabels={B16:['店员工作台','客户确认页','查看客户入口','返回工作台'],B10:['客户入口','交付工作台','查看交付人员工作台','查看客户入口'],B05:['培训负责人','审题工作台','查看审题工作台','查看客户入口'],B18:['客户资料入口','记账员工作台','查看记账员工作台','查看客户入口'],B17:['现场记录','办公室工作台','查看办公室工作台','返回现场入口'],C01:['求职者入口','顾问工作台','查看顾问工作台','查看求职者入口']};
function render(){
 $('name').textContent=cfg.name;$('heading').textContent=titles[code];$('goal').textContent=cfg.goal;
 $('roleName').textContent=roleLabels[code]?.[user()?0:1]||'我的工作区';
 $('workspace').innerHTML=renderWorkspace();$('main').innerHTML=renderers[code]()+serviceHistory();$('notice').hidden=!message;$('notice').textContent=message;$('notice').className='notice'+(isError?' error':'');
 $('roles').innerHTML=roleLabels[code]?btn(roleLabels[code][user()?2:3],'switchRole',false,true):'<span>本项目为个人使用工具，无工作人员入口。</span>';
 $('reviewBoundary').textContent=cfg.boundary;
 document.querySelectorAll('[data-action]').forEach(b=>{b.onclick=()=>act(b.dataset.action);});
 document.querySelectorAll('[data-field]').forEach(el=>el.addEventListener('input',()=>{s.form[el.dataset.field]=el.value;persist();refreshStockActions();const opt=$('recordPicker')?.selectedOptions[0];if(opt)opt.textContent=recordName({state:s})+' · '+recordStatus({state:s});}));
 $('item')?.addEventListener('change',e=>{s.selected=e.target.value;s.form.reason='';persist();render();});
 $('recordPicker')?.addEventListener('change',e=>selectRecord(e.target.value));
 $('stockMode')?.addEventListener('change',e=>{s.form.stockMode=e.target.value;persist();render();});
 $('restoreFile')?.addEventListener('change',readBackup);
}
function act(action){
 syncCurrent();const before=JSON.stringify(exportWorkspace());
 try{
 if(action==='newRecord'){newRecord();}
 else if(action==='switchRole'){s.role=user()?'staff':'user';notify('已切换示例入口；正式产品按各自身份访问。');}
 else if(action==='reset'){s=initial();pendingBackup=null;notify('已重置当前记录，其他记录未改变。');}
 else if(action==='download'){const payload={项目:cfg.name,性质:'交互原型示例结果，非正式交付',状态:s.status,版本:s.version,版本历史:s.history,历次交付:s.deliveries||[],结果:s.report||{表单:s.form,资料状态:s.items,流转状态:s.status},记录:s.events};if(code==='C01'&&s.report){download('岗位简历-示例.txt',s.report.job+'\n\n'+s.report.draft+'\n\n交互原型示例，未经真实专业审核。','text/plain;charset=utf-8');}else{download(code+'-示例结果.json',payload);}notify('示例结果已导出。');}
 else if(action==='backup'){download(code+'-完整备份.json',exportWorkspace());notify('整个列表已备份，包含 '+workspace.records.length+' 条记录。');}
 else if(action==='cancelRestore'){pendingBackup=null;notify('已取消恢复，当前记录未改变。');}
 else if(action==='restore'){guard(pendingBackup,'请先选择有效备份。');guard(pendingBackup.source===JSON.stringify(exportWorkspace()),'预览后记录有变化，请重新选择备份再恢复。');if(pendingBackup.kind==='collection'){workspace=pendingBackup.data;s=workspace.records.find(r=>r.id===workspace.current).state;}else{s=pendingBackup.state;}pendingBackup=null;log('从备份恢复记录');notify('恢复完成，列表与历史已更新。');}
 else if(action==='amend'){guard(['B10','B05','B17','C01'].includes(code)&&user()&&s.status!=='draft','请从客户入口修改已提交资料。');s.status='draft';s.report=null;s.reason='';pendingBackup=null;log('开始修改原始资料，历次交付已保留');notify('请修改资料并重新提交；旧版本仍可在交付历史查看。');}
 else if(code==='B16'){
  if(action==='send'){guard(user(),'请由店员发送。');required('name','customer','content');guard(['draft','rejected'].includes(s.status),'当前版本已经发送，请创建新版后修改。');if(s.status==='rejected')s.version++;s.status='sent';s.history.push({version:s.version,status:'待确认',content:s.form.content});s.sentForm={...s.form};s.confirmedVersion=null;s.waiting=false;log('V'+s.version+' 已发送给 '+s.form.customer);notify('已准备客户确认页。打开原型工具可体验客户入口。');}
  else if(action==='confirm'){guard(!user()&&s.status==='sent','当前版本不可确认。');s.status='confirmed';s.confirmedVersion=s.version;s.history.at(-1).status='已确认';log('客户确认 V'+s.version);notify('已确认这一版，店员会进行印前复核。');}
  else if(action==='reject'){guard(!user()&&s.status==='sent','当前没有待确认校样。');required('reason');s.reason=s.form.reason;s.status='rejected';s.history.at(-1).status='已退回';log('客户退回：'+s.reason);notify('修改意见已记录。');}
  else if(action==='newVersion'){guard(user(),'请由店员创建新版。');s.version++;s.status='draft';s.confirmedVersion=null;s.waiting=true;log('创建 V'+s.version+'，旧回执不再适用于当前版');notify('请修改校样并重新发送。');}
  else if(action==='printCheck'){guard(user()&&s.status==='confirmed'&&s.confirmedVersion===s.version,'当前版本尚未确认，不能登记印前复核。');s.status='checked';log('店员完成 V'+s.version+' 印前复核');notify('已完成印前复核。');}
 }
 else if(['B10','B05','B17','C01'].includes(code)){
  if(action==='submit'){guard(user()&&s.status==='draft','资料已提交；请使用修订入口，不要重复提交。');if(code==='B10'){required('period');number('sales');number('refund');number('ads');}if(code==='B05')required('topic','material');if(code==='B17'){required('name','location','attachment');guard(number('qty')>0,'数量须大于0。');number('price');}if(code==='C01'){required('job','experience');s.form.draft=s.form.experience;}s.status='submitted';s.report=null;s.reason='';log('资料已提交，等待工作人员处理');notify('已提交。可在原型工具体验工作人员交付。');}
  else if(action==='produce'){guard(!user()&&['submitted','revision'].includes(s.status),'请先提交资料或等待客户提出修订，再重新交付。');
   if(code==='B10'){const sales=number('sales'),refund=number('refund'),ads=number('ads');s.report={period:s.form.period,sales,refund,ads,net:Math.round((sales-refund)*100)/100};}
   if(code==='B05'){required('question','answer','source');s.report={topic:s.form.topic,question:s.form.question,answer:s.form.answer,source:s.form.source};}
   if(code==='B17'){required('name','location','attachment');const qty=number('qty'),price=number('price');guard(qty>0,'数量须大于0。');s.report={name:s.form.name,location:s.form.location,qty,price,total:Math.round(qty*price*100)/100,attachment:s.form.attachment};s.version=++s.revision;}
   if(code==='C01'){required('draft');s.report={job:s.form.job,draft:s.form.draft};}
   s.deliveries??=[];s.deliveries.push(JSON.parse(JSON.stringify(s.report)));s.status='delivered';log('工作人员交付新版本');notify('已交付，请在客户入口查看和反馈。');
  }else if(action==='accept'){guard(s.status==='delivered'&&(user()||code==='B17'),'请在客户入口确认待验收结果。');s.status='accepted';log(code==='B17'?'已接收，待外部审批':'客户确认当前交付');notify(code==='B17'?'已接收，待外部审批。':'确认已保存。');}
  else if(action==='revise'){guard(s.status==='delivered'&&(user()||code==='B17'),'请在客户入口反馈待验收结果。');required('reason');s.reason=s.form.reason;s.status='revision';log('退回修订：'+s.reason);notify('已记录反馈，等待重新交付。');}
 }
 else if(code==='B12'){
  const transitions={return:[['draft','out'],'returned','归还已登记，待检查'],ready:[['returned'],'ready','检查通过，恢复可租'],damage:[['returned'],'damaged','发现损坏，暂停出租'],repair:[['damaged'],'returned','维修完成，等待复检'],out:[['ready'],'out','已出库']};const t=transitions[action];guard(t&&t[0].includes(s.status),'当前状态不能执行此操作。');required('equipment');guard(!workspace.records.some(r=>r.id!==workspace.current&&r.state.form.equipment===s.form.equipment),'该器材已在列表中，请切换到原记录。');s.status=t[1];log(s.form.equipment+'：'+t[2]);notify(t[2]);
 }
 else if(code==='B18'){
  const i=+s.selected;
  if(action==='saveClient'){guard(!user()&&s.status==='draft','已收件的客户信息不可改写。');required('client','period');log('保存客户与期间：'+s.form.client+' '+s.form.period);notify('客户与期间已保存。');}
  else if(action==='upload'){guard(user()&&!['等待审核','通过'].includes(s.items[i]),'此资料已提交，请等待审核。');required('client','period','filename');s.files??={};s.files[i]=s.form.filename;s.items[i]='等待审核';s.status='submitted';log('提交资料 '+(i+1)+'：'+s.form.filename);notify('提交完成，等待审核。');}
  else if(action==='approve'){guard(!user()&&s.items[i]==='等待审核','请先提交资料，再由记账员审核。');s.items[i]='通过';log('资料 '+(i+1)+' 审核通过');notify('审核已保存。');}
  else if(action==='reject'){guard(!user()&&s.items[i]==='等待审核','没有待审核资料。');required('reason');s.reasons??={};s.reasons[i]=s.form.reason;s.items[i]='退回补充';log('资料 '+(i+1)+' 退回：'+s.form.reason);notify('退回原因已记录。');}
 }
 else if(code==='C13'){
  if(action==='scan'){required('name','disk');s.status='scanned';s.report={name:s.form.name,source:s.form.disk,groups:[{files:['海边.jpg','旅行-01.jpg'],evidence:'内容一致'},{files:['生日.jpg','生日副本.jpg'],evidence:'哈希匹配，未逐字节复核'},{files:['合影.jpg','备份合影.jpg'],evidence:'待重新连接'}]};log('完成示例扫描，1组待重新连接');notify('已生成示例报告。');}
  else if(action==='recheck'){guard(s.status==='scanned','请先完成扫描。');s.status='verified';s.report.groups[2].evidence='内容一致';log('重新连接后复核完成');notify('复核完成，已更新对应文件状态。');}
 }
 else if(code==='C16'){
  if(action==='calculate'){required('color');guard(!workspace.records.some(r=>r.id!==workspace.current&&r.state.form.color===s.form.color),'该色号已存在，请切换到原记录。');const stock=s.form.stockMode==='unknown'?null:number('stock'),need=number('need');guard((stock===null||Number.isInteger(stock*2))&&Number.isInteger(need*2),'请按半束填写，例如0.5、1、1.5。');s.stock=stock;s.need=need;s.purchase=null;s.status='ready';log('核对库存 '+(stock===null?'待核':stock+' 束')+'，需求 '+need+' 束');notify('缺线清单已更新。');}
  else if(action==='purchase'){guard(stockResultCurrent(),'库存或需求已修改，请核实后重新生成缺线清单。');guard(s.stock!==null&&s.purchase===null,'请先计算缺线；同一次采购不能重复入库。');const n=Math.max(0,s.need-s.stock);guard(n>0,'当前库存充足。');s.stock+=n;s.purchase=n;s.form.stock=String(s.stock);log('采购入库 '+n+' 束');notify('库存已更新。');}
  else if(action==='undoPurchase'){guard(stockResultCurrent(),'库存或需求已修改，请核实后重新生成缺线清单。');guard(s.purchase!==null&&s.stock>=s.purchase,'这次入库不能撤销。');s.stock-=s.purchase;s.form.stock=String(s.stock);log('撤销采购入库 '+s.purchase+' 束');s.purchase=null;notify('已撤销本次入库。');}
  else if(action==='consume'){guard(stockResultCurrent(),'库存或需求已修改，请核实后重新生成缺线清单。');const n=number('used');guard(s.stock!==null&&n>0&&Number.isInteger(n*2)&&n<=s.stock,'用量须为半束的倍数、大于0且不超过库存。');s.stock-=n;s.form.stock=String(s.stock);s.purchase=null;log('实际耗用 '+n+' 束');notify('已扣除实际用量。');}
 }
 else if(code==='C18'){
  if(action==='savePlant'){required('name');s.plants=[{name:s.form.name}];s.status='ready';log('保存植物：'+s.form.name);notify('植物已保存，可以开始记录。');}
  else{guard(s.plants.length>0,'请先保存植物。');if(action==='check'){log('检查完成：'+(s.form.note||'无备注'));notify('检查已记录，未添加浇水记录。');}if(action==='water'){log('已浇水：'+(s.form.note||'无备注'));notify('浇水已记录。');}if(action==='schedule'){required('date');guard(/^\d{4}-\d{2}-\d{2}$/.test(s.form.date),'请选择有效日期。');s.nextDate=s.form.date;log('下次检查：'+s.nextDate);notify('检查日期已保存。');}}
 }
 persist();render();
 }catch(e){workspace=JSON.parse(before);s=workspace.records.find(r=>r.id===workspace.current).state;notify(e.message,true);render();$('notice').focus();}
}
render();
