# Generated by Django 5.2.17 on 2026-09-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerecord',
            name='purpose',
            field=models.CharField(default='original', max_length=16),
        ),
    ]
