# Generated by Django 5.2.17 on 2026-09-20 08:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_filerecord_purpose'),
        ('identity', '0003_codedelivery_invitation_current_delivery'),
        ('proofing', '0002_domain_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot', models.JSONField()),
                ('snapshot_sha256', models.CharField(max_length=64)),
                ('state', models.CharField(default='queued', max_length=16)),
                ('available_at', models.DateTimeField()),
                ('lease_owner', models.CharField(blank=True, max_length=200)),
                ('lease_token', models.UUIDField(null=True)),
                ('lease_expires_at', models.DateTimeField(null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='files.filerecord')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proofing.order')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'available_at'], name='jobs_job_state_7a18ad_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('state__in', ['queued', 'running', 'succeeded', 'failed'])), name='export_job_valid_state')],
            },
        ),
    ]
