'use strict';
const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='os-b04-independent-v1';let db={schema:1,product:'OS-B04',episodes:[Studio.fresh()]},index=0,role='client',tab='brief',clipIndex=0,pending=null,pendingBase='',media=null,mediaUrl=null,message='',isError=false;
try{const raw=localStorage.getItem(key);if(raw)db=Studio.validate(JSON.parse(raw));}catch{message='Saved records could not be loaded. The stored copy is unchanged; import a valid backup before starting new work.';isError=true;}
const episode=()=>db.episodes[index],clip=()=>episode().clips[clipIndex];
const names={draft:'Brief not submitted',editing:'Editor preparing excerpts',review:'Client review',approved:'Text & timing approved',manifest:'Review manifest ready'};
const b=(label,act,disabled=false,secondary=false)=>`<button data-action="${act}" ${disabled?'disabled':''} class="${secondary?'secondary':''}">${esc(label)}</button>`;
const card=(title,body,cls='')=>`<section class="card ${cls}"><h2>${esc(title)}</h2>${body}</section>`;
const row=(label,value)=>`<div class="row"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`;
const empty=t=>`<div class="empty">${esc(t)}</div>`;
const state=s=>`<span class="state ${s}">${esc(s)}</span>`;
function field(id,label,value,type='text',disabled=false){return `<label>${esc(label)}${type==='textarea'?`<textarea id="${id}" ${disabled?'disabled':''}>${esc(value)}</textarea>`:`<input id="${id}" value="${esc(value)}" type="${type}" ${disabled?'disabled':''} ${type==='number'?'min="0" step="1"':''}>`}</label>`;}
const check=(id,label,value=false,disabled=false)=>`<label class="check"><input id="${id}" type="checkbox" ${value?'checked':''} ${disabled?'disabled':''}>${esc(label)}</label>`;
const time=n=>Math.floor(n/60)+':'+String(n%60).padStart(2,'0');
function notice(){const n=$('notice');n.hidden=!message;n.textContent=message;n.className=isError?'error':'';}
function persist(){try{localStorage.setItem(key,JSON.stringify(db));}catch{message='Browser storage is unavailable or full. Download a backup before closing.';isError=true;}}
function saveState(){persist();render();}
function brief(){const e=episode(),locked=e.phase!=='draft'||role!=='client';return `<div class="grid">${card('Episode brief',field('episodeTitle','Episode title',e.title,'text',locked)+field('studioName','Studio / brand',e.brand,'text',locked)+field('sourceRef','Source reference',e.source,'text',locked)+field('duration','Source duration (seconds)',e.duration,'number',locked)+field('glossary','Names & terminology',e.glossary,'textarea',locked)+field('constraints','Brand and context notes',e.notes,'textarea',locked)+check('rights','I have permission to share and repurpose this source',e.rights,locked)+b('Submit brief','brief',locked)+b('Discard unsaved brief','discard',locked,true))}${card('What this package includes',row('Source length','Up to 60 min')+row('Excerpts','3 × 30–90 sec')+row('Format','9:16, one brand template')+row('Supporting files','SRT + chapters + 3 posts')+row('Revision','One consolidated round')+`<p class="note">The proposed test price is USD 240 per episode, before any applicable tax. It is a planning assumption, not a checkout offer. Production delivery is planned within 7 calendar days after usable, authorized source material is complete.</p><p class="note">This walkthrough starts with fictional text. It does not extract a transcript from your source reference.</p><div class="actions">${b('Open excerpts','tab:clips',false,true)}</div>`)}</div>`;}
function selector(){return `<div class="clipbar">${episode().clips.map((c,i)=>`<button data-clip="${i}" class="clip-choice ${i===clipIndex?'active':''}"><span>CLIP 0${i+1}</span><strong>${esc(c.title||'Untitled excerpt')}</strong><em>${esc(c.status)}</em></button>`).join('')}</div>`;}
function portrait(){const c=clip();return `<div class="portrait"><small>TEXT LAYOUT STUDY · 9:16</small><div><div class="wave">${[12,26,35,18,42,31,16,28,40,20,34,13,24,38,18,30,15,42,25,12].map(h=>`<i style="height:${h}px"></i>`).join('')}</div><div class="quote">${esc(c.quote)}</div></div><div class="foot">${esc(episode().brand)} · ${time(c.start)}–${time(c.end)}<br>No video has been rendered</div></div>`;}
function preview(){return card('Excerpt preview',portrait()+`<p class="note">Optional: select a local source video to listen at the selected time. This preview stays on your device and must be attached again after refresh. It does not produce a clip.</p><label>Local source preview<input id="sourceFile" type="file" accept="video/*"></label>${mediaUrl?`<p class="note">${esc(media.name)}</p><video id="media" controls src="${esc(mediaUrl)}"></video>${b('Play selected range','play',false,true)}`:''}`,'preview');}
function clips(){const e=episode(),c=clip(),locked=role!=='editor'||e.phase!=='editing';return selector()+`<div class="grid"><div>${card('Shape the excerpt',`${state(c.status)} ${e.version>2?'<p class="feedback">More than one revision: confirm scope before further production.</p>':''}${c.feedback?`<p class="feedback">Client feedback: ${esc(c.feedback)}</p>`:''}`+field('clipTitle','Clip title',c.title,'text',locked)+`<div class="two">${field('start','In point (seconds)',c.start,'number',locked)}${field('end','Out point (seconds)',c.end,'number',locked)}</div>`+field('quote','Exact source excerpt',c.quote,'textarea',locked)+field('context','Context & limitations to preserve',c.context,'textarea',locked)+field('post','Accompanying post',c.post,'textarea',locked)+check('checked','I checked the excerpt, names and context against the source',c.checked,locked)+`<div class="actions">${b('Save excerpt','saveClip',locked)}${b('Discard unsaved fields','discard',locked,true)}</div><p class="note">Save before switching excerpts or sections. Sending freezes all three excerpts as one review version.</p>`)}${card('Episode chapters',field('chapters','Chapter notes',e.chapters,'textarea',locked)+b('Save chapter notes','saveChapters',locked))}${card('Send the review',`<p>All three excerpts need a source check before the client can review this version.</p>${b('Send three excerpts for review','send',locked)}${b('Start new revision','revision',role!=='editor'||!['review','approved','manifest'].includes(e.phase),true)}<p class="note">Starting a revision keeps the previous review and clears all current approvals.</p>`)}</div><div>${preview()}</div></div>`;}
function review(){const e=episode(),c=clip();if(['draft','editing'].includes(e.phase))return empty('No frozen review is ready. The editor must check and send all three excerpts first.');const locked=role!=='client'||e.phase!=='review'||c.status!=='pending';return selector()+`<div class="grid">${card('Review this excerpt',`<p>${state(c.status)} · Version ${e.version} · ${time(c.start)}–${time(c.end)}</p><h3>${esc(c.title)}</h3><p class="snapshot">${esc(c.quote)}</p><h3>Keep this context</h3><div class="context">${esc(c.context)}</div><h3>Post copy</h3><p>${esc(c.post)}</p>${check('read','I reviewed the excerpt, context and post copy',false,locked)}${field('feedback','Change request',c.feedback,'textarea',locked)}<div class="actions">${b('Approve this excerpt','approve',locked)}${b('Request changes','changes',locked,true)}</div><p class="note">Approval covers this text and timing only. Rendered media still needs a separate quality check before production delivery.</p>`)}<div>${card('Package status',e.clips.map(c=>row(c.title,c.status)).join('')+`<div class="actions">${b('Start new revision','revision',role!=='editor',true)}${b('Open handoff','tab:handoff',false,true)}</div>`)}${card('Chapter notes',`<div class="snapshot">${esc(e.chapters)}</div>`)}</div></div>`;}
function handoff(){const e=episode();return `<div class="grid"><div>${card('Review handoff',`<p>${state(e.phase==='approved'||e.phase==='manifest'?'Text review approved':'Awaiting approvals')}</p><p>Prepare a manifest only after all three excerpts in the current version are approved.</p>${b('Prepare review manifest','manifest',role!=='editor'||e.phase!=='approved')}${e.manifest?`<div class="actions">${b('Download review manifest','manifestDownload')}</div><p class="note">Version ${e.manifest.version}. The manifest explicitly records that media has not been rendered.</p>`:''}`)}${card('Sample working files',e.clips.map((c,i)=>`<article class="asset"><div><strong>Clip 0${i+1} · ${esc(c.title)}</strong><p class="note">Single-cue SRT example; source excerpt and post text.</p></div><div class="actions">${b('Clip '+(i+1)+' SRT','srt:'+i,!e.manifest,true)}${b('Clip '+(i+1)+' copy','copy:'+i,!e.manifest,true)}</div></article>`).join('')+`<div class="actions">${b('Download chapter notes','chapterDownload',!e.manifest,true)}</div>`)}</div>${card('Still needed for production delivery',`<p class="feedback">This is not a completed delivery.</p>${['Three rendered MP4 clips, checked at full resolution','Source-checked, accurately timed captions','Editable production project and reusable brand settings','Actual audio, framing and subtitle quality checks','Customer receipt of the complete agreed package'].map(x=>row(x,'Not produced here')).join('')}<p class="note">A JSON manifest or a checked box cannot stand in for these assets. No order is marked delivered by this prototype.</p>`)}</div>`;}
function activity(){const e=episode();return `<div class="grid">${card('Activity',e.events.length?`<ol class="timeline">${e.events.slice().reverse().map(v=>`<li>${esc(v.action)}<time>v${v.version} · ${esc(v.time)}</time></li>`).join('')}</ol>`:empty('No actions recorded yet.'))}${card('Frozen review versions',e.history.length?e.history.slice().reverse().map(h=>`<details><summary>Version ${h.version} · ${esc(h.sentAt)}</summary>${h.clips.map(c=>`<h3>${esc(c.title)} · ${time(c.start)}–${time(c.end)}</h3><div class="snapshot">${esc(c.quote)}</div>`).join('')}<p class="note">${h.decisions.map(d=>esc(d.id+': '+d.status)).join(' · ')}</p></details>`).join(''):empty('Sending a review creates an immutable content snapshot.'))}</div>`;}
function render(){const e=episode();$('title').textContent=e.title||'Untitled episode';$('phase').textContent=names[e.phase];$('roleLabel').textContent=role==='editor'?'EDITOR WORKSPACE':'CLIENT WORKSPACE';$('subtitle').textContent=e.brand+' · Version '+e.version+' · '+(e.rights?'Source authorization declared':'Source authorization pending');$('episodes').innerHTML=db.episodes.map((e,i)=>`<button class="episode ${i===index?'active':''}" data-episode="${i}"><strong>${esc(e.title||'Untitled episode')}</strong><span>${esc(names[e.phase])} · v${e.version}</span></button>`).join('');$('tabs').innerHTML=[['brief','01 Brief'],['clips','02 Excerpts'],['review','03 Review'],['handoff','04 Handoff'],['activity','Activity']].map(([id,label])=>`<button data-tab="${id}" class="${tab===id?'selected':''}">${label}</button>`).join('');$('main').innerHTML=({brief,clips,review,handoff,activity})[tab]();notice();
 document.querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>act(el.dataset.action));
 document.querySelectorAll('[data-tab]').forEach(el=>el.onclick=()=>navigate(()=>tab=el.dataset.tab));
 document.querySelectorAll('[data-clip]').forEach(el=>el.onclick=()=>navigate(()=>clipIndex=Number(el.dataset.clip)));
 document.querySelectorAll('[data-episode]').forEach(el=>el.onclick=()=>navigate(()=>{index=Number(el.dataset.episode);clipIndex=0;tab='brief';clearMedia();pending=null;}));
 $('sourceFile')?.addEventListener('change',event=>{const f=event.target.files[0];if(!f)return;if(dirty()){message='Save or discard your edits before attaching media.';isError=true;notice();event.target.value='';return;}if(!f.type.startsWith('video/')||f.size>200*1024*1024){message='Choose a video file up to 200 MB for this preview.';isError=true;notice();return;}clearMedia();media=f;mediaUrl=URL.createObjectURL(f);render();});
 $('media')?.addEventListener('timeupdate',()=>{if($('media').currentTime>=clip().end)$('media').pause();});
 $('clientRole').disabled=role==='client';$('editorRole').disabled=role==='editor';$('restorePreview').innerHTML=pending?`<p class="note">Replace this browser's workspace with ${pending.episodes.length} episode(s)? Current source media will be detached. Export a backup first if you need to keep the current workspace.</p><button id="confirmRestore">Confirm replacement</button> <button class="secondary" id="cancelRestore">Cancel</button>`:'';
 if($('confirmRestore'))$('confirmRestore').onclick=()=>{try{if(JSON.stringify(db)!==pendingBase)throw Error('Records changed after preview. Select the backup again.');Studio.validate(pending);db=Studio.copy(pending);pending=null;index=0;clipIndex=0;tab='brief';clearMedia();message='Workspace restored.';isError=false;saveState();}catch(e){message=e.message;isError=true;notice();}};
 if($('cancelRestore'))$('cancelRestore').onclick=()=>{pending=null;render();};
}
function dirty(){if(tab==='brief'&&role==='client'&&episode().phase==='draft'){const e=episode();return ['episodeTitle','studioName','sourceRef','duration','constraints','glossary'].some((id,i)=>$(id).value!==String(e[['title','brand','source','duration','notes','glossary'][i]]))||$('rights').checked!==e.rights;}if(tab!=='clips'||role!=='editor'||episode().phase!=='editing')return false;const c=clip();return ['clipTitle','start','end','quote','context','post'].some((id,i)=>$(id)&&$(id).value!==String(c[['title','start','end','quote','context','post'][i]]))||$('checked')?.checked!==c.checked||$('chapters')?.value!==episode().chapters;}
function navigate(fn){if(dirty()){message='Submit/save or discard your edits before changing sections.';isError=true;notice();return;}fn();message='';isError=false;render();}
function clearMedia(){if(mediaUrl)URL.revokeObjectURL(mediaUrl);mediaUrl=null;media=null;}
function download(name,value,type='application/json'){const blob=new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function act(action){isError=false;message='';try{const e=episode(),c=clip();let payload={};
 if(action.startsWith('tab:')){navigate(()=>tab=action.split(':')[1]);return;}
 if(action==='discard'){render();return;}
 if(action==='play'){const v=$('media');if(!v)throw Error('Attach a source preview first.');if(!Number.isFinite(v.duration)||c.end>v.duration)throw Error('The selected video is not ready or is shorter than this excerpt.');v.currentTime=c.start;v.play().catch(()=>{message='Playback could not start. Use the video controls.';isError=true;notice();});return;}
 if(action==='brief')payload={title:$('episodeTitle').value,brand:$('studioName').value,source:$('sourceRef').value,duration:$('duration').value,notes:$('constraints').value,glossary:$('glossary').value,rights:$('rights').checked};
 if(action==='saveClip')payload={clipId:c.id,title:$('clipTitle').value,start:$('start').value,end:$('end').value,quote:$('quote').value,context:$('context').value,post:$('post').value,checked:$('checked').checked};
 if(action==='saveChapters'){if(['clipTitle','start','end','quote','context','post'].some((id,i)=>$(id).value!==String(c[['title','start','end','quote','context','post'][i]]))||$('checked').checked!==c.checked)throw Error('Save the excerpt first; that also saves chapter edits.');payload={chapters:$('chapters').value};}
 if(action==='approve')payload={clipId:c.id,version:e.version,read:$('read').checked};
 if(action==='changes')payload={clipId:c.id,version:e.version,feedback:$('feedback').value};
 if(action==='send'&&dirty())throw Error('Save or discard your edits before sending the review.');
 if(action==='manifestDownload'){if(!e.manifest)throw Error('Prepare a manifest first.');download('review-v'+e.version+'.json',e.manifest);message='Review manifest downloaded. Production media is still outstanding.';notice();return;}
 if(action.startsWith('srt:')||action.startsWith('copy:')){if(!e.manifest)throw Error('Prepare a manifest first.');const [kind,i]=action.split(':'),sample=e.manifest.clips[Number(i)];download(sample.id+'-v'+e.version+(kind==='srt'?'.srt':'.txt'),kind==='srt'?Studio.srt(sample):sample.title+'\n\nSOURCE EXCERPT\n'+sample.quote+'\n\nCONTEXT\n'+sample.context+'\n\nPOST\n'+sample.post,'text/plain;charset=utf-8');message='Sample working file downloaded; no media was rendered.';notice();return;}
 if(action==='chapterDownload'){if(!e.manifest)throw Error('Prepare a manifest first.');download('chapters-v'+e.version+'.txt',e.manifest.chapters,'text/plain;charset=utf-8');return;}
 let updated=Studio.transition(e,action,payload,role);if(action==='saveClip'&&$('chapters')&&$('chapters').value!==e.chapters)updated=Studio.transition(updated,'saveChapters',{chapters:$('chapters').value},role);db.episodes[index]=updated;pending=null;if(action==='brief')tab='clips';if(action==='send')tab='review';if(action==='revision')tab='clips';message=action==='manifest'?'Review manifest prepared. Actual video delivery has not occurred.':action==='revision'?'New revision started. Previous decisions remain in history; current excerpts need fresh review.':'Saved.';saveState();
 }catch(e){message=e.message;isError=true;notice();}}
$('newEpisode').onclick=()=>{if(db.episodes.length>=20){message='This prototype supports 20 episodes per workspace.';isError=true;notice();return;}navigate(()=>{const e=Studio.fresh();e.title='';e.brand='';e.source='';db.episodes.push(e);index=db.episodes.length-1;clipIndex=0;tab='brief';clearMedia();pending=null;persist();});};
$('clientRole').onclick=()=>navigate(()=>role='client');$('editorRole').onclick=()=>navigate(()=>role='editor');
$('backup').onclick=()=>{try{if(dirty())throw Error('Submit/save or discard edits before exporting a backup.');Studio.validate(db);if(new Blob([JSON.stringify(db,null,2)]).size>2000000)throw Error('Backup exceeds the 2 MB prototype limit.');download('episode-desk-backup.json',db);message='Browser text and review history exported. Source videos are not included.';isError=false;}catch(e){message=e.message;isError=true;}notice();};
$('restore').onchange=async event=>{if(dirty()){message='Submit/save or discard edits before importing a backup.';isError=true;notice();event.target.value='';return;}pending=null;try{const f=event.target.files[0];if(!f)return;if(f.size>2000000)throw Error('Backup exceeds the 2 MB prototype limit.');const value=JSON.parse(await f.text());Studio.validate(value);pending=value;pendingBase=JSON.stringify(db);message='Backup validated. Check the replacement scope before continuing.';isError=false;}catch(e){message=e instanceof SyntaxError?'Invalid JSON. Existing records are unchanged.':e.message;isError=true;}render();};
render();
