# Generated by Django 5.2.17 on 2026-09-20 05:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('identity', '0001_initial'),
        ('proofing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receiver', models.CharField(max_length=254)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('code_hash', models.CharField(blank=True, max_length=64)),
                ('code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('code_browser_hash', models.CharField(blank=True, max_length=64)),
                ('code_sent_at', models.DateTimeField(blank=True, null=True)),
                ('code_sends', models.PositiveSmallIntegerField(default=0)),
                ('code_attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='files.filerecord')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='proofing.order')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('verification_method', models.CharField(default='receiver_code', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_sessions', to='identity.invitation')),
            ],
        ),
    ]
