# Generated by Django 5.2.17 on 2026-09-20 06:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_invitation_externalsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('browser_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='code_deliveries', to='identity.invitation')),
            ],
        ),
        migrations.AddField(
            model_name='invitation',
            name='current_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.codedelivery'),
        ),
    ]
