# Generated by Django 5.2.17 on 2026-09-20 06:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('identity', '0003_codedelivery_invitation_current_delivery'),
        ('proofing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('awaiting_confirmation', 'awaiting_confirmation'), ('confirmed', 'confirmed'), ('returned', 'returned'), ('revoked', 'revoked')], default='draft', max_length=30),
        ),
        migrations.CreateModel(
            name='ConfirmationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.CharField(max_length=254)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='confirmation_request', to='identity.invitation')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('confirmed', 'confirmed'), ('returned', 'returned'), ('revoked', 'revoked'), ('superseded', 'superseded')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('verification_method', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('external_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='identity.externalsession')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='proofing.confirmationrequest')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProofVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='files.filerecord')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='proofing.order')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='PrintReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('confirmation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proofing.confirmationevent')),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='print_review', to='proofing.proofversion')),
            ],
        ),
        migrations.AddField(
            model_name='confirmationrequest',
            name='version',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='confirmation_request', to='proofing.proofversion'),
        ),
        migrations.AddField(
            model_name='order',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='proofing.proofversion'),
        ),
        migrations.AddConstraint(
            model_name='confirmationevent',
            constraint=models.UniqueConstraint(condition=models.Q(('decision__in', ['confirmed', 'returned'])), fields=('request',), name='unique_request_decision'),
        ),
        migrations.AddConstraint(
            model_name='confirmationevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', True), ('decision__in', ['confirmed', 'returned']), ('external_session__isnull', False)), models.Q(('actor__isnull', False), ('decision__in', ['revoked', 'superseded']), ('external_session__isnull', True)), _connector='OR'), name='event_actual_actor_kind'),
        ),
        migrations.AddConstraint(
            model_name='confirmationevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decision', 'returned'), _negated=True), models.Q(('reason', ''), _negated=True), _connector='OR'), name='returned_requires_reason'),
        ),
        migrations.AddConstraint(
            model_name='proofversion',
            constraint=models.UniqueConstraint(fields=('order', 'sequence'), name='unique_order_version_sequence'),
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION b16_immutable_history() RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'B16 historical rows are immutable' USING ERRCODE = '23514';
                END;
                $$ LANGUAGE plpgsql;
                CREATE TRIGGER immutable_proof_version BEFORE UPDATE OR DELETE ON proofing_proofversion
                    FOR EACH ROW EXECUTE FUNCTION b16_immutable_history();
                CREATE TRIGGER immutable_confirmation_event BEFORE UPDATE OR DELETE ON proofing_confirmationevent
                    FOR EACH ROW EXECUTE FUNCTION b16_immutable_history();
                CREATE TRIGGER immutable_print_review BEFORE UPDATE OR DELETE ON proofing_printreview
                    FOR EACH ROW EXECUTE FUNCTION b16_immutable_history();
            """,
            reverse_sql="""
                DROP TRIGGER immutable_print_review ON proofing_printreview;
                DROP TRIGGER immutable_confirmation_event ON proofing_confirmationevent;
                DROP TRIGGER immutable_proof_version ON proofing_proofversion;
                DROP FUNCTION b16_immutable_history();
            """,
        ),
    ]
